"""Custom-structure generator — builds structures instead of picking them.

Enumerates 1–4 leg combinations over the LIQUID contracts of a chain, keeps
only defined-risk shapes inside the user's loss budget, scores each by
view-conditional expected value per rupee of risk, dedupes by payoff shape,
and names the survivors (a recognised pattern gets its textbook name; the
rest are honestly labelled "custom structure").

This is what separates an advisor from a menu: if the chain's own pricing
offers a better risk shape than any classic, it will be found.
"""
from __future__ import annotations

import itertools
import math

from ..analytics.metrics import liquid_smile_spread
from ..analytics.view import MarketView
from ..core.models import Chain, Leg, StrategyResult
from ..core.payoff import evaluate
from .naming import classify

MAX_UNIVERSE = 26            # liquid contracts considered (keeps combos sane)


def _universe(chain: Chain, min_oi: int, max_spread_pct: float) -> list:
    """Most-liquid contracts nearest the money — the tradable subset."""
    q = chain.liquid(min_oi=min_oi, max_spread_pct=max_spread_pct)
    q.sort(key=lambda x: (abs(x.strike - chain.spot), -x.oi))
    return q[:MAX_UNIVERSE]


def _combos(univ: list, max_legs: int):
    """Candidate leg-sets: verticals, flies, condors, straddle/strangle-like
    pairs and ratio shapes — generated by structure, not brute force over
    every subset (which explodes and mostly yields junk)."""
    calls = sorted([q for q in univ if q.is_call], key=lambda q: q.strike)
    puts = sorted([q for q in univ if not q.is_call], key=lambda q: q.strike)

    # 1-leg
    for q in univ:
        for side in (1, -1):
            yield [Leg(q.strike, q.is_call, side, 1)]

    # 2-leg same-right verticals + ratios
    for grp in (calls, puts):
        for a, b in itertools.combinations(grp, 2):
            for s in (1, -1):
                yield [Leg(a.strike, a.is_call, s, 1),
                       Leg(b.strike, b.is_call, -s, 1)]
            if max_legs >= 2:
                yield [Leg(a.strike, a.is_call, 1, 1),
                       Leg(b.strike, b.is_call, -1, 2)]
                yield [Leg(a.strike, a.is_call, -1, 1),
                       Leg(b.strike, b.is_call, 1, 2)]

    # 2-leg cross-right (straddle / strangle / risk reversal)
    for c in calls:
        for p in puts:
            for s in (1, -1):
                yield [Leg(c.strike, True, s, 1), Leg(p.strike, False, s, 1)]
            yield [Leg(c.strike, True, 1, 1), Leg(p.strike, False, -1, 1)]
            yield [Leg(c.strike, True, -1, 1), Leg(p.strike, False, 1, 1)]

    if max_legs < 3:
        return
    # 3-leg butterflies (incl. broken wings)
    for grp in (calls, puts):
        for a, b, c in itertools.combinations(grp, 3):
            yield [Leg(a.strike, a.is_call, 1, 1), Leg(b.strike, b.is_call, -1, 2),
                   Leg(c.strike, c.is_call, 1, 1)]

    if max_legs < 4:
        return
    # 4-leg iron condors / butterflies (2 puts below, 2 calls above)
    lo_puts = [p for p in puts if p.strike <= max(c.strike for c in calls)]
    for p1, p2 in itertools.combinations(lo_puts, 2):
        for c1, c2 in itertools.combinations(calls, 2):
            if p2.strike > c1.strike:
                continue
            yield [Leg(p1.strike, False, 1, 1), Leg(p2.strike, False, -1, 1),
                   Leg(c1.strike, True, -1, 1), Leg(c2.strike, True, 1, 1)]
    # 4-leg single-right condors
    for grp in (calls, puts):
        for a, b, c, d in itertools.combinations(grp, 4):
            yield [Leg(a.strike, a.is_call, 1, 1), Leg(b.strike, a.is_call, -1, 1),
                   Leg(c.strike, a.is_call, -1, 1), Leg(d.strike, a.is_call, 1, 1)]


SMILE_TOLERANCE = 5.0        # vol points of smile the EV term tolerates


def ev_confidence(smile_spread: float | None) -> float:
    """How much of the EV term to trust, given how steep this chain's smile is.

    Legs are PRICED at their own IVs off the smile but VALUED under one blended
    sigma (see payoff._sigma_for), so any multi-strike structure books the
    smile's curvature as edge. The steeper the smile, the more of the EV is
    artifact rather than opportunity:

        <=  5 vol pts   full weight
           10 vol pts   half
           20 vol pts   quarter

    This is a MITIGATION, not a fix. It matters most when ranking a whole
    universe: without it, sorting many chains by EV surfaces the steepest-smile
    chains first — i.e. it ranks names by how wrong the model is on them. The
    real fix is building the terminal density from the smile itself
    (Breeden-Litzenberger), after which this damping should be removed.
    """
    if smile_spread is None or smile_spread <= SMILE_TOLERANCE:
        return 1.0
    return 1.0 / (1.0 + (smile_spread - SMILE_TOLERANCE) / SMILE_TOLERANCE)


def score_of(res: StrategyResult, smile_spread: float | None = None) -> float:
    """Ranking score, shared by generated and classic structures.

        score = EV / std(payoff)      RISK-ADJUSTED edge (a trade "Sharpe")
              + 0.10 * POP fraction   hit rate
              + 0.05 * capped RR      payoff shape
              - 0.02 * leg count      friction + fill risk

    Why EV per unit of payoff VOLATILITY and not EV per rupee of max loss:
    the latter is maximised by the cheapest lottery ticket, so it ranks "buy
    the furthest OTM call" first every time a view is bullish — an artefact
    of the denominator, not a real edge (verified in testing). Dividing by
    the payoff's own standard deviation asks the professional question: how
    much edge per unit of uncertainty?

    Under a fairly-priced chain with a NEUTRAL view the EV term is ~0 for
    every structure — that is the correct answer, not a bug — and the
    ordering degrades gracefully to POP/shape quality.
    """
    denom = res.payoff_std if res.payoff_std > 1e-9 else (
        res.max_loss if res.max_loss not in (0.0, float("inf"))
        else max(res.margin_estimate, 1.0))
    sharpe = ev_confidence(smile_spread) * res.expected_value / denom
    rr = min(res.rr_ratio, 3.0) / 3.0 if res.rr_ratio else 0.0
    return sharpe + 0.10 * (res.pop_pct / 100.0) + 0.05 * rr \
        - 0.02 * len(res.legs)


def _shape_key(res: StrategyResult, chain: Chain) -> tuple:
    """Payoff-shape fingerprint for dedupe — two structures that pay the same
    at every kink are the same trade regardless of how they are assembled."""
    from ..core.payoff import payoff_at
    pts = sorted({l.strike for l in res.legs})
    lo, hi = chain.spot * 0.8, chain.spot * 1.2
    probes = [lo] + pts + [hi]
    return tuple(round(payoff_at(res.legs, p), 1) for p in probes)


def generate(chain: Chain, view: MarketView, top_n: int = 5,
             max_legs: int = 4, max_loss_rupees: float = 25_000.0,
             min_pop: float = 25.0, min_rr: float = 0.15,
             min_oi: int = 100, max_spread_pct: float = 25.0,
             allow_undefined_risk: bool = False) -> list[StrategyResult]:
    """Return the best `top_n` generated structures under the view."""
    univ = _universe(chain, min_oi, max_spread_pct)
    if len(univ) < 2:
        return []

    seen: set[tuple] = set()
    pool: list[StrategyResult] = []
    tilt = view.tilt
    smile = liquid_smile_spread(chain)      # computed once, not per candidate

    for legs in _combos(univ, max_legs):
        if sum(l.qty for l in legs) > 6:
            continue
        try:
            res = evaluate(legs, chain, tilt=tilt, use_exec_prices=True,
                           is_custom=True, vol_mult=view.vol_multiplier,
                           source="generated")
        except Exception:
            continue

        # risk gates
        if not allow_undefined_risk and res.max_loss == float("inf"):
            continue
        if res.max_loss <= 0 or res.max_loss > max_loss_rupees:
            continue
        if res.max_profit != float("inf") and res.max_profit <= res.friction:
            continue
        if res.pop_pct < min_pop:
            continue
        if res.rr_ratio and res.rr_ratio < min_rr:
            continue

        key = _shape_key(res, chain)
        if key in seen:
            continue
        seen.add(key)

        res.score = score_of(res, smile)
        name = classify(res.legs)
        res.is_custom = name == "custom structure"
        res.name = name
        pool.append(res)

    pool.sort(key=lambda r: -r.score)
    out = pool[:top_n]
    for r in out:
        r.rationale = _rationale(r, view)
    return out


def _rationale(res: StrategyResult, view: MarketView) -> str:
    bits = []
    d = res.greeks.get("delta", 0)
    if abs(d) > 1:
        lean = "bullish" if d > 0 else "bearish"
        agrees = (d > 0) == (view.bias >= 0) and abs(view.bias) > 0.05
        bits.append(f"net delta {d:+.0f} ({lean} lean"
                    + (f", agrees with the {view.direction} view)" if agrees
                       else ")"))
    v = res.greeks.get("vega", 0)
    if abs(v) > 1:
        bits.append(f"vega {v:+.0f}/pt — "
                    f"{'long' if v > 0 else 'short'} volatility")
    th = res.greeks.get("theta", 0)
    if abs(th) > 1:
        bits.append(f"theta {th:+.0f}/day")
    if res.net_premium < 0:
        bits.append(f"opens for a credit of Rs.{abs(res.net_premium)*res.lot_size:,.0f}")
    bits.append(f"risk capped at Rs.{res.max_loss:,.0f}/lot")
    return "; ".join(bits)
